### PR TITLE
Rewards: Adjust Miner/Masternode reward ratio - Add sentinel version check

### PR DESCRIPTION
**Pull request by semiformal**
### Masternode rewards
This change sets a block height in the future upon which the Miner/Masternode reward ratio will be adjusted. **The parameters in this change should not be considered final**. They are easily adjusted. This change also adds a sentinel version check. 

Parameters can be easily adjusted but they currently are:
- Activate Block: 55009 (Approximately April 28th) **Not Final**

Rewards set by this PR - **Not Final**
- **Miner: 690** (was 4830)
- **Masternode: 10350** (was 6210)
- Miner / Masternode ratio is 6.25% / 93.75% (was 43.75% / 56.25%)

This change is basically a softfork as long as `SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT` is not active. Any pool/miner that is using the old client will generate rewards using the old scheme, these blocks will not be rejected from the network unless SPORK_8 is active. If SPORK_8 is active, nodes generating blocks with the wrong miner/node reward will be banned very quickly. 

### Sentinel Fix
The sentinel change updates the local sentinel code to require a minimum sentinel version number. If this version is not correct the Masternode will eventually go into the WATCHDOG_EXPIRED state. 

This code also adds a local change that will prevent the vote-conf command from working if the node is in the WATCHDOG_EXPIRED state. This is important as out of date nodes can incorrectly vote to delete proposals. 

Minimum sentinel version is currently "1.2.0". The sentinel repo needs to be updated with this new version number. Code snippet below. 

In sentinel/lib/config.py line: 13

```
sentinel_version = "1.2.0"
```

### CODE REVIEW

**Comment by alejandromgk** [comment]
So to clarify, we are targeting a flat 5% of the total rewards for the miners, right?

Everything looks good, we'll start testing this ASAP.

**Comment by semiformal** [comment]
@alejandromgk Yes the change sets 5% for miners 75% Masternodes 

Updated PR with sentinel fix. Sentinel fix is not a fork and should not affect the network itself, but it helps to be deployed along with a required update, since it's actually hard to enforce from a network standpoint.

**Comment by alejandromgk** [comment]
@semiformal So testing went without issues.

We tested that:

- Once the block height defined on  `consensus.nMasternodePaymentsIncreaseBlock` is reached, the payments change to the new rules.
- If `SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT` is disabled, both protocol and rules can coexist, once it's enabled, they cannot (once the block height is greater than the block height defined on `consensus.nMasternodePaymentsIncreaseBlock`).
- If `SPORK_10_MASTERNODE_PAY_UPDATED_NODES` is disabled, MN on protocol `70212` can still receive payments, if it gets enabled, their status change to `UPDATE_REQUIRED` and they no longer are eligible to receive payments, until they upgrade.
- With `consensus.nMasternodePaymentsIncreaseBlock` reached and `SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT` enabled, miners and normal nodes on protocol `70212` eventually get banned from peers running protocol `70213` for trying to propagate wrong blocks and blocks mined with old rules are not added to the chain.
- The updated to the sentinel ping worked as intended, and if an outdated sentinel version is running, the status of the MN changes to `WATCHDOG_EXPIRED`. If `SPORK_14_REQUIRE_SENTINEL_FLAG` is enabled they are not eligible to receive payments, until they update their sentinel.

Do you think we missed one scenario?

**Comment by alejandromgk** [comment]
@semiformal or @breakcrypto 

As you might be aware, it was decided to push the date forward. Could you update the block height on `consensus.nMasternodePaymentsIncreaseBlock` to `50000`. 

And also, could you bump the version on [clientversion.h](https://github.com/PACCommunity/PAC/blob/master/src/clientversion.h#L19)

After this, everything will be in place and we can merge this and start building the wallets.

**Comment by semiformal** [comment]
@alejandromgk 
Updates made. Cheers. I bumped the copyright to 2018 too. looks like configure.ac needed to be updated in addition to clientversion.h fyi.

**Comment by alejandromgk** [comment]
@semiformal Awesome, thanks man! 

Merging it now.

**Pull request merged**
